require_empty_hand: true
allow_chair_hopping: true
blacklisted_worlds:
  - world_the_end
  - world_nether
show_errors: true
errors:
  already_sitting: You're already sitting down!
  occupied_chair: That chair is already occupied!
  blacklisted_world: You cannot sit in ${world}!