name: ${project.name}
description: ${project.description}
version: ${project.version}
main: net.nexia.chairsEvolved.ChairsEvolved
api-version: 1.21
website: https://www.playnexia.net/
authors: [ ItsGeppy ]
